name: Rebase onto latest release
on:
  workflow_dispatch:
  schedule:
    # 8am UTC is 2am or 3am in Houston.
    - cron: 0 8 * * *

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: docs
          # Fetch all history.
          fetch-depth: 0
      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/microsoft/TypeScript.git
          git fetch upstream master
          git checkout upstream/master
      - name: Remove workflows
        run: |
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git rm -r .github/workflows
          git commit -m 'Remove workflows'
      - name: Rebase
        run: git rebase HEAD docs
      - name: Push if changed
        run: git diff origin/docs --quiet || git push -f origin docs
